### ISSUE TITLE
Are there any frontend themes that ship with the package?

### ISSUE THREAD

**Issue by impactcolor** [conedevelopment/bazar#181]
Not a feature request or bug.  Just a question.
Are there any frontend themes that ship with the package?  Or any themes that can be purchased for it?

**Comment by iamgergo** [comment]
Hey,

We've got an unfinished TEST front-end them/application.

But since we are planning to roll a custom UI system for Bazar and it's core package, probably we won't maintain it anymore. Are you still interested? Because we can open up the repository, and you might find some useful code there.

Thanks!

**Comment by ven7ura** [comment]
Hey! I am interested. I have worked on some front-end for the package, but your code might help me do best practices.

**Comment by bobitza** [comment]
I'm need also some example on frontend how to use, to show products, and how to call functions to display media, categories etc..

**Comment by Almusamim** [comment]
> Hey,
> 
> We've got an unfinished TEST front-end them/application.
> 
> But since we are planning to roll a custom UI system for Bazar and it's core package, probably we won't maintain it anymore. Are you still interested? Because we can open up the repository, and you might find some useful code there.
> 
> Thanks!

Hello, where can i find the repo?

thanks

**Comment by LarryBarker** [comment]
@iamgergo I'd be interested as well 🙏 Thanks!
